apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "whoami-spec-teste"
  description: "Artifacts generator via Spec."
  annotations:
    github.com/project-slug: veecode-homolog/whoami-spec-teste
    backstage.io/techdocs-ref: dir:..
    github.com/workflows: publish.yml,remove.yml
    kong-manager/service-name: app.whoami-spec-teste.80
    kong-manager/instance: cluster-playrole-vtg
    kong-manager/spec : openapi-swagger.yaml
spec:
  type: devops
  lifecycle: experimental
  owner: "group:default/admin"
  providesApis:
    - whoami-spec-teste
